- name: Terminate find.exe process on Windows
  hosts: all
  gather_facts: no

  tasks:
  - name: Get the PID of find.exe
    win_shell: |
      $process = Get-Process -Name find -ErrorAction SilentlyContinue
      if ($process) { $process.Id } else { "Not found" }
    register: result

  - name: Terminate find.exe process
    win_shell: |
      Stop-Process -Id {{ result.stdout }} -Force
    when: result.stdout != "Not found"
    async: 20
    poll: 0    
    
  - name: Change directory to C:\JOYSEC
    win_shell: |
      chdir C:\\JOYSEC
    become: yes
    become_user: jcadmin

  - name: Execute the PowerShell script on the remote server
    win_shell: |
      powershell.exe -NoProfile -ExecutionPolicy Bypass -File C:\\JOYSEC\\excute.ps1
    become: yes
    become_user: jcadmin
    async: 120
    poll: 0

  - name: Pause for 100 seconds
    pause:
      seconds: 100

  - name: Get current date
    set_fact:
      current_date: "{{ lookup('pipe', 'date +%Y%m%d') }}"

  - name: Find log files
    win_shell: Get-ChildItem -Path "C:\\JOYSEC\\*{{ current_date }}*.log" | Select-Object -ExpandProperty FullName
    register: log_files

  - name: Fetch log files from remote server
    fetch:
      src: "{{ item }}"
      dest: "/seclog/"
      flat: yes
    with_items: "{{ log_files.stdout_lines }}"
