- name: Ansible Playbook for Windows Server
  hosts: all
  tasks:
    - name: Create a directory if it does not exist
      win_file:
        path: C:\\joycity-system\\winlogbeat
        state: directory

    - name: Copy winlogbeat-configure.ps1 file to the remote server
      win_copy:
        src: /winlogbeat/for_all-winlogbeat-configure.ps1
        dest: C:\\joycity-system\\winlogbeat\\for_all-winlogbeat-configure.ps1

    - name: Execute the winlogbeat-configure PowerShell script on the remote server
      win_shell:
        powershell.exe -NoProfile -ExecutionPolicy Bypass -File C:\\joycity-system\\winlogbeat\\for_all-winlogbeat-configure.ps1
      become: yes
      become_user: jcadmin
      async: 120
      poll: 0